version: "2.1"

defaults: &defaults
  docker:
    - image: circleci/node

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          paths:
            - /src/node-modules
          key: "npm-packages"
      - run:
          command: |
            npm i  
            npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run:
          command: |
            npm run test

  analyze:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            npm run audit

workflows:
  build-npm:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
